package: cache_warmup
version: '3.3.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cache_warmup

page:
    title: translate:title
    perm: admin
    popup: true
    hidden: true
    subpages:
        warmup:
            title: translate:title
            popup: true
            hidden: true
        generator:
            title: generator
            hidden: true
            hasLayout: false

pages:
    system/cache_warmup:
        title: translate:title
        perm: admin

console_commands:
    cache_warmup:warmup: rex_cache_warmup_command

requires:
    redaxo: '^5.0'
    php: '>=5.5'

# define conflicts: prevents packages from update to avoid breaking changes
# https://github.com/FriendsOfREDAXO/cache_warmup/pull/55#issuecomment-280906737
conflicts:
    packages:
        media_manager: '>=3'
        metainfo: '>=3'
        structure: '>=3'
        yform: '>=3'
